name: ChocoHills
author: zwrumpy
main: me.zwrumpy.chocohills.ChocoHills
version: ${project.version}
api-version: 1.17
depend:
- Slimefun
commands:
  chtool:
    description:
    usage: /<command>
    permission: chtool.use